use super::{GroupInfo, SubsystemInfo};

pub const SINAN: SubsystemInfo = SubsystemInfo {
    code: "SINAN",
    name: "Sistema de Informação de Agravos de Notificação",
    description: Some("Base de dados de doenças e agravos de notificação compulsória (SINAN)."),
    long_description: Some(
        "O Sistema de Informação de Agravos de Notificação (SINAN) é alimentado principalmente \
pelas notificações e investigações de casos de doenças e agravos listados na lista nacional \
de doenças de notificação compulsória (Portaria de Consolidação nº 4, de 28 de setembro de 2017). \
Estados e municípios também podem incluir outros problemas de saúde relevantes para suas regiões. \
Seu uso efetivo possibilita o diagnóstico dinâmico da ocorrência de eventos na população, subsidia \
explicações causais e indica riscos aos quais as pessoas estão expostas. O SINAN contribui para \
o planejamento em saúde, definição de prioridades de intervenção e avaliação do impacto de ações \
e políticas públicas.",
    ),
    url: Some("https://portalsinan.saude.gov.br/"),
    groups: &[
        GroupInfo {
            code: "ACBI",
            name: "Acidente de trabalho com material biológico",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "ACGR",
            name: "Acidente de trabalho",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "ANIM",
            name: "Acidente por Animais Peçonhentos",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "ANTR",
            name: "Atendimento Antirrabico",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "BOTU",
            name: "Botulismo",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "CANC",
            name: "Câncer relacionado ao trabalho",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "CHAG",
            name: "Doença de Chagas Aguda",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "CHIK",
            name: "Febre de Chikungunya",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "COLE",
            name: "Cólera",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "COQU",
            name: "Coqueluche",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "DENG",
            name: "Dengue",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "DERM",
            name: "Dermatoses ocupacionais",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "DIFT",
            name: "Difteria",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "ESQU",
            name: "Esquistossomose",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "EXAN",
            name: "Doença exantemática",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "FMAC",
            name: "Febre Maculosa",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "FTIF",
            name: "Febre Tifóide",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "HANS",
            name: "Hanseníase",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "HANT",
            name: "Hantavirose",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "HEPA",
            name: "Hepatites Virais",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "IEXO",
            name: "Intoxicação Exógena",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "INFL",
            name: "Influenza Pandêmica",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "LEIV",
            name: "Leishmaniose Visceral",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "LEPT",
            name: "Leptospirose",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "LERD",
            name: "LER/Dort",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "LTAN",
            name: "Leishmaniose Tegumentar Americana",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "MALA",
            name: "Malária",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "MENI",
            name: "Meningite",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "MENT",
            name: "Transtornos mentais relacionados ao trabalho",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "NTRA",
            name: "Notificação de Tracoma",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "PAIR",
            name: "Perda auditiva por ruído relacionado ao trabalho",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "PEST",
            name: "Peste",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "PFAN",
            name: "Paralisia Flácida Aguda",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "PNEU",
            name: "Pneumoconioses relacionadas ao trabalho",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "RAIV",
            name: "Raiva",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "SDTA",
            name: "Surto Doenças Transmitidas por Alimentos",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "SIFA",
            name: "Sífilis Adquirida",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "SIFC",
            name: "Sífilis Congênita",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "SIFG",
            name: "Sífilis em Gestante",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "SRC",
            name: "Síndrome da Rubéola Congênita",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TETA",
            name: "Tétano Acidental",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TETN",
            name: "Tétano Neonatal",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TOXC",
            name: "Toxoplasmose Congênita",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TOXG",
            name: "Toxoplasmose Gestacional",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TRAC",
            name: "Inquérito de Tracoma",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "TUBE",
            name: "Tuberculose",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "VARC",
            name: "Varicela",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "VIOL",
            name: "Violência doméstica, sexual e/ou outras violências",
            description: None,
            long_description: None,
            url: None,
        },
        GroupInfo {
            code: "ZIKA",
            name: "Zika Vírus",
            description: None,
            long_description: None,
            url: None,
        },
    ],
};
